#!/usr/bin/env bash

set -uo pipefail

readonly REPORT_DIR="${STAGE3C_REPORT_DIR:-reports}"
readonly DIAGNOSTICS_DIR="${STAGE3C_DIAGNOSTICS_DIR:-diagnostics}"
readonly ENV_FILE="$(mktemp "${TMPDIR:-/tmp}/sociyohub-stage3c-env.XXXXXX")"
readonly LIVE_REPORT="${REPORT_DIR}/live.json"
readonly LIVE_META="${REPORT_DIR}/live.meta.json"

services_started=false

finish() {
  local command_status=$?
  local teardown_status=0
  trap - EXIT INT TERM

  rm -f "$ENV_FILE"
  if [ "$services_started" = true ]; then
    if ! supabase stop --no-backup >"${DIAGNOSTICS_DIR}/supabase-stop.log" 2>&1; then
      teardown_status=$?
      printf '%s\n' "Stage 3C teardown failed; see ${DIAGNOSTICS_DIR}/supabase-stop.log." >&2
    fi
  fi

  if [ "$command_status" -ne 0 ]; then
    exit "$command_status"
  fi
  exit "$teardown_status"
}
trap finish EXIT INT TERM

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf '%s\n' "Stage 3C local runtime requires '$1'." >&2
    exit 127
  fi
}

require_command bun
require_command docker
require_command supabase

mkdir -p "$REPORT_DIR" "$DIAGNOSTICS_DIR"
docker info >"${DIAGNOSTICS_DIR}/docker-info.log" 2>&1 || {
  printf '%s\n' "Docker is unavailable; see ${DIAGNOSTICS_DIR}/docker-info.log." >&2
  exit 1
}

supabase start --debug >"${DIAGNOSTICS_DIR}/supabase-start.log" 2>&1
services_started=true

# Apply every checked-in migration to a clean disposable database. Production
# and shared credentials are never read or accepted by this runner.
supabase db reset --no-seed >"${DIAGNOSTICS_DIR}/supabase-reset.log" 2>&1
supabase status -o env >"$ENV_FILE" 2>"${DIAGNOSTICS_DIR}/supabase-status.log"

set -a
# The file is generated by the local CLI and is deleted by the EXIT trap.
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

: "${API_URL:?Local API_URL missing from supabase status}"
: "${SERVICE_ROLE_KEY:?Local SERVICE_ROLE_KEY missing from supabase status}"
: "${ANON_KEY:?Local ANON_KEY missing from supabase status}"

case "$API_URL" in
  http://127.0.0.1:*|http://localhost:*) ;;
  *)
    printf '%s\n' "Refusing to run Stage 3C against a non-local database URL." >&2
    exit 1
    ;;
esac

export ALLOW_SOCIOHUB_LIVE_STAGE3C=true
export SOCIOHUB_TEST_SUPABASE_URL="$API_URL"
export SOCIOHUB_TEST_SUPABASE_SERVICE_ROLE_KEY="$SERVICE_ROLE_KEY"
export SOCIOHUB_TEST_SUPABASE_PUBLISHABLE_KEY="$ANON_KEY"

# Prevent a caller's shared environment from matching the disposable target.
if [ -n "${SUPABASE_URL:-}" ] && [ "$SUPABASE_URL" = "$SOCIOHUB_TEST_SUPABASE_URL" ]; then
  printf '%s\n' "Refusing to run because the test URL matches SUPABASE_URL." >&2
  exit 1
fi

bun scripts/stage3c-canonical-case-contract.ts
bun scripts/verify-stage3c-live-core-source.ts
bun scripts/verify-stage3c-live-matrix-93-source.ts

commit_sha="$(git rev-parse HEAD)"
printf '{"commit":"%s"}\n' "$commit_sha" >"$LIVE_META"

# Keep the JSON report on failure. `set -e` is intentionally not used so the
# canonical report validators can still inspect and reject a partial run.
live_status=0
bunx vitest run tests/integration/billing-stage3c-live.test.ts \
  --reporter=default --reporter=json --outputFile="$LIVE_REPORT" || live_status=$?

report_status=0
if [ ! -s "$LIVE_REPORT" ]; then
  printf '%s\n' "Stage 3C live report is missing or empty." >&2
  report_status=1
else
  bun scripts/verify-stage3c-live-core-report.ts "$LIVE_REPORT" || report_status=$?
  bun scripts/verify-stage3c-live-matrix-93-report.ts "$LIVE_REPORT" \
    --expected-sha="$commit_sha" --meta="$LIVE_META" || report_status=$?
fi

if [ "$live_status" -ne 0 ]; then
  exit "$live_status"
fi
exit "$report_status"