/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as SocietyRouteImport } from './routes/_society'
import { Route as ResidentRouteImport } from './routes/_resident'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingPlanRouteImport } from './routes/onboarding.plan'
import { Route as OnboardingPendingRouteImport } from './routes/onboarding.pending'
import { Route as OnboardingJoinRouteImport } from './routes/onboarding.join'
import { Route as OnboardingCreateRouteImport } from './routes/onboarding.create'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as ApiSupportChatRouteImport } from './routes/api/support-chat'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthPhoneOtpRouteImport } from './routes/_auth/phone-otp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as SocietySocietyVisitorsRouteImport } from './routes/_society/society.visitors'
import { Route as SocietySocietyVerificationsRouteImport } from './routes/_society/society.verifications'
import { Route as SocietySocietyVehiclesRouteImport } from './routes/_society/society.vehicles'
import { Route as SocietySocietyTeamRouteImport } from './routes/_society/society.team'
import { Route as SocietySocietySetupRouteImport } from './routes/_society/society.setup'
import { Route as SocietySocietyResidentsRouteImport } from './routes/_society/society.residents'
import { Route as SocietySocietyReportsRouteImport } from './routes/_society/society.reports'
import { Route as SocietySocietyPollsRouteImport } from './routes/_society/society.polls'
import { Route as SocietySocietyPlanRequiredRouteImport } from './routes/_society/society.plan-required'
import { Route as SocietySocietyMaintenanceRouteImport } from './routes/_society/society.maintenance'
import { Route as SocietySocietyLedgerRouteImport } from './routes/_society/society.ledger'
import { Route as SocietySocietyLeaderboardRouteImport } from './routes/_society/society.leaderboard'
import { Route as SocietySocietyFlatsRouteImport } from './routes/_society/society.flats'
import { Route as SocietySocietyExpensesRouteImport } from './routes/_society/society.expenses'
import { Route as SocietySocietyDigestRouteImport } from './routes/_society/society.digest'
import { Route as SocietySocietyDashboardRouteImport } from './routes/_society/society.dashboard'
import { Route as SocietySocietyCustomFieldsRouteImport } from './routes/_society/society.custom-fields'
import { Route as SocietySocietyBlocksRouteImport } from './routes/_society/society.blocks'
import { Route as SocietySocietyBillingRouteImport } from './routes/_society/society.billing'
import { Route as SocietySocietyBillStudioRouteImport } from './routes/_society/society.bill-studio'
import { Route as SocietySocietyApprovalsRouteImport } from './routes/_society/society.approvals'
import { Route as SocietySocietyAnnouncementsRouteImport } from './routes/_society/society.announcements'
import { Route as ResidentAppVisitorsRouteImport } from './routes/_resident/app.visitors'
import { Route as ResidentAppVehiclesRouteImport } from './routes/_resident/app.vehicles'
import { Route as ResidentAppTrustRouteImport } from './routes/_resident/app.trust'
import { Route as ResidentAppServicesRouteImport } from './routes/_resident/app.services'
import { Route as ResidentAppProfileRouteImport } from './routes/_resident/app.profile'
import { Route as ResidentAppPollsRouteImport } from './routes/_resident/app.polls'
import { Route as ResidentAppPlanRequiredRouteImport } from './routes/_resident/app.plan-required'
import { Route as ResidentAppNoticesRouteImport } from './routes/_resident/app.notices'
import { Route as ResidentAppLedgerRouteImport } from './routes/_resident/app.ledger'
import { Route as ResidentAppHelpdeskRouteImport } from './routes/_resident/app.helpdesk'
import { Route as ResidentAppGuardRouteImport } from './routes/_resident/app.guard'
import { Route as ResidentAppFeedRouteImport } from './routes/_resident/app.feed'
import { Route as ResidentAppFamilyRouteImport } from './routes/_resident/app.family'
import { Route as ResidentAppEmergencyRouteImport } from './routes/_resident/app.emergency'
import { Route as ResidentAppDuesRouteImport } from './routes/_resident/app.dues'
import { Route as ResidentAppDashboardRouteImport } from './routes/_resident/app.dashboard'
import { Route as ResidentAppBillsRouteImport } from './routes/_resident/app.bills'
import { Route as ResidentAppActivityRouteImport } from './routes/_resident/app.activity'
import { Route as ResidentAppAchievementsRouteImport } from './routes/_resident/app.achievements'
import { Route as AdminAdminWithdrawalsRouteImport } from './routes/_admin/admin.withdrawals'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AdminAdminRazorpayRouteImport } from './routes/_admin/admin.razorpay'
import { Route as AdminAdminPlansRouteImport } from './routes/_admin/admin.plans'
import { Route as AdminAdminIncomeRouteImport } from './routes/_admin/admin.income'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin.dashboard'
import { Route as AdminAdminAdsRouteImport } from './routes/_admin/admin.ads'
import { Route as ApiPublicHooksRunBillingRouteImport } from './routes/api/public/hooks/run-billing'
import { Route as ResidentAppFeedPostIdRouteImport } from './routes/_resident/app.feed.$postId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietyRoute = SocietyRouteImport.update({
  id: '/_society',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentRoute = ResidentRouteImport.update({
  id: '/_resident',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPlanRoute = OnboardingPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPendingRoute = OnboardingPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingJoinRoute = OnboardingJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCreateRoute = OnboardingCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OnboardingRoute,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportChatRoute = ApiSupportChatRouteImport.update({
  id: '/api/support-chat',
  path: '/api/support-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPhoneOtpRoute = AuthPhoneOtpRouteImport.update({
  id: '/phone-otp',
  path: '/phone-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const SocietySocietyVisitorsRoute = SocietySocietyVisitorsRouteImport.update({
  id: '/society/visitors',
  path: '/society/visitors',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyVerificationsRoute =
  SocietySocietyVerificationsRouteImport.update({
    id: '/society/verifications',
    path: '/society/verifications',
    getParentRoute: () => SocietyRoute,
  } as any)
const SocietySocietyVehiclesRoute = SocietySocietyVehiclesRouteImport.update({
  id: '/society/vehicles',
  path: '/society/vehicles',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyTeamRoute = SocietySocietyTeamRouteImport.update({
  id: '/society/team',
  path: '/society/team',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietySetupRoute = SocietySocietySetupRouteImport.update({
  id: '/society/setup',
  path: '/society/setup',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyResidentsRoute = SocietySocietyResidentsRouteImport.update({
  id: '/society/residents',
  path: '/society/residents',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyReportsRoute = SocietySocietyReportsRouteImport.update({
  id: '/society/reports',
  path: '/society/reports',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyPollsRoute = SocietySocietyPollsRouteImport.update({
  id: '/society/polls',
  path: '/society/polls',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyPlanRequiredRoute =
  SocietySocietyPlanRequiredRouteImport.update({
    id: '/society/plan-required',
    path: '/society/plan-required',
    getParentRoute: () => SocietyRoute,
  } as any)
const SocietySocietyMaintenanceRoute =
  SocietySocietyMaintenanceRouteImport.update({
    id: '/society/maintenance',
    path: '/society/maintenance',
    getParentRoute: () => SocietyRoute,
  } as any)
const SocietySocietyLedgerRoute = SocietySocietyLedgerRouteImport.update({
  id: '/society/ledger',
  path: '/society/ledger',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyLeaderboardRoute =
  SocietySocietyLeaderboardRouteImport.update({
    id: '/society/leaderboard',
    path: '/society/leaderboard',
    getParentRoute: () => SocietyRoute,
  } as any)
const SocietySocietyFlatsRoute = SocietySocietyFlatsRouteImport.update({
  id: '/society/flats',
  path: '/society/flats',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyExpensesRoute = SocietySocietyExpensesRouteImport.update({
  id: '/society/expenses',
  path: '/society/expenses',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyDigestRoute = SocietySocietyDigestRouteImport.update({
  id: '/society/digest',
  path: '/society/digest',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyDashboardRoute = SocietySocietyDashboardRouteImport.update({
  id: '/society/dashboard',
  path: '/society/dashboard',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyCustomFieldsRoute =
  SocietySocietyCustomFieldsRouteImport.update({
    id: '/society/custom-fields',
    path: '/society/custom-fields',
    getParentRoute: () => SocietyRoute,
  } as any)
const SocietySocietyBlocksRoute = SocietySocietyBlocksRouteImport.update({
  id: '/society/blocks',
  path: '/society/blocks',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyBillingRoute = SocietySocietyBillingRouteImport.update({
  id: '/society/billing',
  path: '/society/billing',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyBillStudioRoute =
  SocietySocietyBillStudioRouteImport.update({
    id: '/society/bill-studio',
    path: '/society/bill-studio',
    getParentRoute: () => SocietyRoute,
  } as any)
const SocietySocietyApprovalsRoute = SocietySocietyApprovalsRouteImport.update({
  id: '/society/approvals',
  path: '/society/approvals',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyAnnouncementsRoute =
  SocietySocietyAnnouncementsRouteImport.update({
    id: '/society/announcements',
    path: '/society/announcements',
    getParentRoute: () => SocietyRoute,
  } as any)
const ResidentAppVisitorsRoute = ResidentAppVisitorsRouteImport.update({
  id: '/app/visitors',
  path: '/app/visitors',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppVehiclesRoute = ResidentAppVehiclesRouteImport.update({
  id: '/app/vehicles',
  path: '/app/vehicles',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppTrustRoute = ResidentAppTrustRouteImport.update({
  id: '/app/trust',
  path: '/app/trust',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppServicesRoute = ResidentAppServicesRouteImport.update({
  id: '/app/services',
  path: '/app/services',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppProfileRoute = ResidentAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppPollsRoute = ResidentAppPollsRouteImport.update({
  id: '/app/polls',
  path: '/app/polls',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppPlanRequiredRoute = ResidentAppPlanRequiredRouteImport.update({
  id: '/app/plan-required',
  path: '/app/plan-required',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppNoticesRoute = ResidentAppNoticesRouteImport.update({
  id: '/app/notices',
  path: '/app/notices',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppLedgerRoute = ResidentAppLedgerRouteImport.update({
  id: '/app/ledger',
  path: '/app/ledger',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppHelpdeskRoute = ResidentAppHelpdeskRouteImport.update({
  id: '/app/helpdesk',
  path: '/app/helpdesk',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppGuardRoute = ResidentAppGuardRouteImport.update({
  id: '/app/guard',
  path: '/app/guard',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppFeedRoute = ResidentAppFeedRouteImport.update({
  id: '/app/feed',
  path: '/app/feed',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppFamilyRoute = ResidentAppFamilyRouteImport.update({
  id: '/app/family',
  path: '/app/family',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppEmergencyRoute = ResidentAppEmergencyRouteImport.update({
  id: '/app/emergency',
  path: '/app/emergency',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppDuesRoute = ResidentAppDuesRouteImport.update({
  id: '/app/dues',
  path: '/app/dues',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppDashboardRoute = ResidentAppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppBillsRoute = ResidentAppBillsRouteImport.update({
  id: '/app/bills',
  path: '/app/bills',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppActivityRoute = ResidentAppActivityRouteImport.update({
  id: '/app/activity',
  path: '/app/activity',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppAchievementsRoute = ResidentAppAchievementsRouteImport.update({
  id: '/app/achievements',
  path: '/app/achievements',
  getParentRoute: () => ResidentRoute,
} as any)
const AdminAdminWithdrawalsRoute = AdminAdminWithdrawalsRouteImport.update({
  id: '/admin/withdrawals',
  path: '/admin/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRazorpayRoute = AdminAdminRazorpayRouteImport.update({
  id: '/admin/razorpay',
  path: '/admin/razorpay',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPlansRoute = AdminAdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIncomeRoute = AdminAdminIncomeRouteImport.update({
  id: '/admin/income',
  path: '/admin/income',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAdsRoute = AdminAdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksRunBillingRoute =
  ApiPublicHooksRunBillingRouteImport.update({
    id: '/api/public/hooks/run-billing',
    path: '/api/public/hooks/run-billing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResidentAppFeedPostIdRoute = ResidentAppFeedPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => ResidentAppFeedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gdpr': typeof GdprRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/phone-otp': typeof AuthPhoneOtpRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/onboarding/create': typeof OnboardingCreateRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/onboarding/pending': typeof OnboardingPendingRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/admin/ads': typeof AdminAdminAdsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/income': typeof AdminAdminIncomeRoute
  '/admin/plans': typeof AdminAdminPlansRoute
  '/admin/razorpay': typeof AdminAdminRazorpayRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/withdrawals': typeof AdminAdminWithdrawalsRoute
  '/app/achievements': typeof ResidentAppAchievementsRoute
  '/app/activity': typeof ResidentAppActivityRoute
  '/app/bills': typeof ResidentAppBillsRoute
  '/app/dashboard': typeof ResidentAppDashboardRoute
  '/app/dues': typeof ResidentAppDuesRoute
  '/app/emergency': typeof ResidentAppEmergencyRoute
  '/app/family': typeof ResidentAppFamilyRoute
  '/app/feed': typeof ResidentAppFeedRouteWithChildren
  '/app/guard': typeof ResidentAppGuardRoute
  '/app/helpdesk': typeof ResidentAppHelpdeskRoute
  '/app/ledger': typeof ResidentAppLedgerRoute
  '/app/notices': typeof ResidentAppNoticesRoute
  '/app/plan-required': typeof ResidentAppPlanRequiredRoute
  '/app/polls': typeof ResidentAppPollsRoute
  '/app/profile': typeof ResidentAppProfileRoute
  '/app/services': typeof ResidentAppServicesRoute
  '/app/trust': typeof ResidentAppTrustRoute
  '/app/vehicles': typeof ResidentAppVehiclesRoute
  '/app/visitors': typeof ResidentAppVisitorsRoute
  '/society/announcements': typeof SocietySocietyAnnouncementsRoute
  '/society/approvals': typeof SocietySocietyApprovalsRoute
  '/society/bill-studio': typeof SocietySocietyBillStudioRoute
  '/society/billing': typeof SocietySocietyBillingRoute
  '/society/blocks': typeof SocietySocietyBlocksRoute
  '/society/custom-fields': typeof SocietySocietyCustomFieldsRoute
  '/society/dashboard': typeof SocietySocietyDashboardRoute
  '/society/digest': typeof SocietySocietyDigestRoute
  '/society/expenses': typeof SocietySocietyExpensesRoute
  '/society/flats': typeof SocietySocietyFlatsRoute
  '/society/leaderboard': typeof SocietySocietyLeaderboardRoute
  '/society/ledger': typeof SocietySocietyLedgerRoute
  '/society/maintenance': typeof SocietySocietyMaintenanceRoute
  '/society/plan-required': typeof SocietySocietyPlanRequiredRoute
  '/society/polls': typeof SocietySocietyPollsRoute
  '/society/reports': typeof SocietySocietyReportsRoute
  '/society/residents': typeof SocietySocietyResidentsRoute
  '/society/setup': typeof SocietySocietySetupRoute
  '/society/team': typeof SocietySocietyTeamRoute
  '/society/vehicles': typeof SocietySocietyVehiclesRoute
  '/society/verifications': typeof SocietySocietyVerificationsRoute
  '/society/visitors': typeof SocietySocietyVisitorsRoute
  '/app/feed/$postId': typeof ResidentAppFeedPostIdRoute
  '/api/public/hooks/run-billing': typeof ApiPublicHooksRunBillingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gdpr': typeof GdprRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/phone-otp': typeof AuthPhoneOtpRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/onboarding/create': typeof OnboardingCreateRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/onboarding/pending': typeof OnboardingPendingRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/admin/ads': typeof AdminAdminAdsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/income': typeof AdminAdminIncomeRoute
  '/admin/plans': typeof AdminAdminPlansRoute
  '/admin/razorpay': typeof AdminAdminRazorpayRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/withdrawals': typeof AdminAdminWithdrawalsRoute
  '/app/achievements': typeof ResidentAppAchievementsRoute
  '/app/activity': typeof ResidentAppActivityRoute
  '/app/bills': typeof ResidentAppBillsRoute
  '/app/dashboard': typeof ResidentAppDashboardRoute
  '/app/dues': typeof ResidentAppDuesRoute
  '/app/emergency': typeof ResidentAppEmergencyRoute
  '/app/family': typeof ResidentAppFamilyRoute
  '/app/feed': typeof ResidentAppFeedRouteWithChildren
  '/app/guard': typeof ResidentAppGuardRoute
  '/app/helpdesk': typeof ResidentAppHelpdeskRoute
  '/app/ledger': typeof ResidentAppLedgerRoute
  '/app/notices': typeof ResidentAppNoticesRoute
  '/app/plan-required': typeof ResidentAppPlanRequiredRoute
  '/app/polls': typeof ResidentAppPollsRoute
  '/app/profile': typeof ResidentAppProfileRoute
  '/app/services': typeof ResidentAppServicesRoute
  '/app/trust': typeof ResidentAppTrustRoute
  '/app/vehicles': typeof ResidentAppVehiclesRoute
  '/app/visitors': typeof ResidentAppVisitorsRoute
  '/society/announcements': typeof SocietySocietyAnnouncementsRoute
  '/society/approvals': typeof SocietySocietyApprovalsRoute
  '/society/bill-studio': typeof SocietySocietyBillStudioRoute
  '/society/billing': typeof SocietySocietyBillingRoute
  '/society/blocks': typeof SocietySocietyBlocksRoute
  '/society/custom-fields': typeof SocietySocietyCustomFieldsRoute
  '/society/dashboard': typeof SocietySocietyDashboardRoute
  '/society/digest': typeof SocietySocietyDigestRoute
  '/society/expenses': typeof SocietySocietyExpensesRoute
  '/society/flats': typeof SocietySocietyFlatsRoute
  '/society/leaderboard': typeof SocietySocietyLeaderboardRoute
  '/society/ledger': typeof SocietySocietyLedgerRoute
  '/society/maintenance': typeof SocietySocietyMaintenanceRoute
  '/society/plan-required': typeof SocietySocietyPlanRequiredRoute
  '/society/polls': typeof SocietySocietyPollsRoute
  '/society/reports': typeof SocietySocietyReportsRoute
  '/society/residents': typeof SocietySocietyResidentsRoute
  '/society/setup': typeof SocietySocietySetupRoute
  '/society/team': typeof SocietySocietyTeamRoute
  '/society/vehicles': typeof SocietySocietyVehiclesRoute
  '/society/verifications': typeof SocietySocietyVerificationsRoute
  '/society/visitors': typeof SocietySocietyVisitorsRoute
  '/app/feed/$postId': typeof ResidentAppFeedPostIdRoute
  '/api/public/hooks/run-billing': typeof ApiPublicHooksRunBillingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_resident': typeof ResidentRouteWithChildren
  '/_society': typeof SocietyRouteWithChildren
  '/gdpr': typeof GdprRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/phone-otp': typeof AuthPhoneOtpRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/onboarding/create': typeof OnboardingCreateRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/onboarding/pending': typeof OnboardingPendingRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_admin/admin/ads': typeof AdminAdminAdsRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/income': typeof AdminAdminIncomeRoute
  '/_admin/admin/plans': typeof AdminAdminPlansRoute
  '/_admin/admin/razorpay': typeof AdminAdminRazorpayRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_admin/admin/withdrawals': typeof AdminAdminWithdrawalsRoute
  '/_resident/app/achievements': typeof ResidentAppAchievementsRoute
  '/_resident/app/activity': typeof ResidentAppActivityRoute
  '/_resident/app/bills': typeof ResidentAppBillsRoute
  '/_resident/app/dashboard': typeof ResidentAppDashboardRoute
  '/_resident/app/dues': typeof ResidentAppDuesRoute
  '/_resident/app/emergency': typeof ResidentAppEmergencyRoute
  '/_resident/app/family': typeof ResidentAppFamilyRoute
  '/_resident/app/feed': typeof ResidentAppFeedRouteWithChildren
  '/_resident/app/guard': typeof ResidentAppGuardRoute
  '/_resident/app/helpdesk': typeof ResidentAppHelpdeskRoute
  '/_resident/app/ledger': typeof ResidentAppLedgerRoute
  '/_resident/app/notices': typeof ResidentAppNoticesRoute
  '/_resident/app/plan-required': typeof ResidentAppPlanRequiredRoute
  '/_resident/app/polls': typeof ResidentAppPollsRoute
  '/_resident/app/profile': typeof ResidentAppProfileRoute
  '/_resident/app/services': typeof ResidentAppServicesRoute
  '/_resident/app/trust': typeof ResidentAppTrustRoute
  '/_resident/app/vehicles': typeof ResidentAppVehiclesRoute
  '/_resident/app/visitors': typeof ResidentAppVisitorsRoute
  '/_society/society/announcements': typeof SocietySocietyAnnouncementsRoute
  '/_society/society/approvals': typeof SocietySocietyApprovalsRoute
  '/_society/society/bill-studio': typeof SocietySocietyBillStudioRoute
  '/_society/society/billing': typeof SocietySocietyBillingRoute
  '/_society/society/blocks': typeof SocietySocietyBlocksRoute
  '/_society/society/custom-fields': typeof SocietySocietyCustomFieldsRoute
  '/_society/society/dashboard': typeof SocietySocietyDashboardRoute
  '/_society/society/digest': typeof SocietySocietyDigestRoute
  '/_society/society/expenses': typeof SocietySocietyExpensesRoute
  '/_society/society/flats': typeof SocietySocietyFlatsRoute
  '/_society/society/leaderboard': typeof SocietySocietyLeaderboardRoute
  '/_society/society/ledger': typeof SocietySocietyLedgerRoute
  '/_society/society/maintenance': typeof SocietySocietyMaintenanceRoute
  '/_society/society/plan-required': typeof SocietySocietyPlanRequiredRoute
  '/_society/society/polls': typeof SocietySocietyPollsRoute
  '/_society/society/reports': typeof SocietySocietyReportsRoute
  '/_society/society/residents': typeof SocietySocietyResidentsRoute
  '/_society/society/setup': typeof SocietySocietySetupRoute
  '/_society/society/team': typeof SocietySocietyTeamRoute
  '/_society/society/vehicles': typeof SocietySocietyVehiclesRoute
  '/_society/society/verifications': typeof SocietySocietyVerificationsRoute
  '/_society/society/visitors': typeof SocietySocietyVisitorsRoute
  '/_resident/app/feed/$postId': typeof ResidentAppFeedPostIdRoute
  '/api/public/hooks/run-billing': typeof ApiPublicHooksRunBillingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gdpr'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/support'
    | '/terms'
    | '/welcome'
    | '/forgot-password'
    | '/login'
    | '/phone-otp'
    | '/reset-password'
    | '/api/support-chat'
    | '/checkout/$planId'
    | '/onboarding/create'
    | '/onboarding/join'
    | '/onboarding/pending'
    | '/onboarding/plan'
    | '/onboarding/'
    | '/admin/ads'
    | '/admin/dashboard'
    | '/admin/income'
    | '/admin/plans'
    | '/admin/razorpay'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/achievements'
    | '/app/activity'
    | '/app/bills'
    | '/app/dashboard'
    | '/app/dues'
    | '/app/emergency'
    | '/app/family'
    | '/app/feed'
    | '/app/guard'
    | '/app/helpdesk'
    | '/app/ledger'
    | '/app/notices'
    | '/app/plan-required'
    | '/app/polls'
    | '/app/profile'
    | '/app/services'
    | '/app/trust'
    | '/app/vehicles'
    | '/app/visitors'
    | '/society/announcements'
    | '/society/approvals'
    | '/society/bill-studio'
    | '/society/billing'
    | '/society/blocks'
    | '/society/custom-fields'
    | '/society/dashboard'
    | '/society/digest'
    | '/society/expenses'
    | '/society/flats'
    | '/society/leaderboard'
    | '/society/ledger'
    | '/society/maintenance'
    | '/society/plan-required'
    | '/society/polls'
    | '/society/reports'
    | '/society/residents'
    | '/society/setup'
    | '/society/team'
    | '/society/vehicles'
    | '/society/verifications'
    | '/society/visitors'
    | '/app/feed/$postId'
    | '/api/public/hooks/run-billing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gdpr'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/support'
    | '/terms'
    | '/welcome'
    | '/forgot-password'
    | '/login'
    | '/phone-otp'
    | '/reset-password'
    | '/api/support-chat'
    | '/checkout/$planId'
    | '/onboarding/create'
    | '/onboarding/join'
    | '/onboarding/pending'
    | '/onboarding/plan'
    | '/onboarding'
    | '/admin/ads'
    | '/admin/dashboard'
    | '/admin/income'
    | '/admin/plans'
    | '/admin/razorpay'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/achievements'
    | '/app/activity'
    | '/app/bills'
    | '/app/dashboard'
    | '/app/dues'
    | '/app/emergency'
    | '/app/family'
    | '/app/feed'
    | '/app/guard'
    | '/app/helpdesk'
    | '/app/ledger'
    | '/app/notices'
    | '/app/plan-required'
    | '/app/polls'
    | '/app/profile'
    | '/app/services'
    | '/app/trust'
    | '/app/vehicles'
    | '/app/visitors'
    | '/society/announcements'
    | '/society/approvals'
    | '/society/bill-studio'
    | '/society/billing'
    | '/society/blocks'
    | '/society/custom-fields'
    | '/society/dashboard'
    | '/society/digest'
    | '/society/expenses'
    | '/society/flats'
    | '/society/leaderboard'
    | '/society/ledger'
    | '/society/maintenance'
    | '/society/plan-required'
    | '/society/polls'
    | '/society/reports'
    | '/society/residents'
    | '/society/setup'
    | '/society/team'
    | '/society/vehicles'
    | '/society/verifications'
    | '/society/visitors'
    | '/app/feed/$postId'
    | '/api/public/hooks/run-billing'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_resident'
    | '/_society'
    | '/gdpr'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/support'
    | '/terms'
    | '/welcome'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/phone-otp'
    | '/_auth/reset-password'
    | '/api/support-chat'
    | '/checkout/$planId'
    | '/onboarding/create'
    | '/onboarding/join'
    | '/onboarding/pending'
    | '/onboarding/plan'
    | '/onboarding/'
    | '/_admin/admin/ads'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/income'
    | '/_admin/admin/plans'
    | '/_admin/admin/razorpay'
    | '/_admin/admin/users'
    | '/_admin/admin/withdrawals'
    | '/_resident/app/achievements'
    | '/_resident/app/activity'
    | '/_resident/app/bills'
    | '/_resident/app/dashboard'
    | '/_resident/app/dues'
    | '/_resident/app/emergency'
    | '/_resident/app/family'
    | '/_resident/app/feed'
    | '/_resident/app/guard'
    | '/_resident/app/helpdesk'
    | '/_resident/app/ledger'
    | '/_resident/app/notices'
    | '/_resident/app/plan-required'
    | '/_resident/app/polls'
    | '/_resident/app/profile'
    | '/_resident/app/services'
    | '/_resident/app/trust'
    | '/_resident/app/vehicles'
    | '/_resident/app/visitors'
    | '/_society/society/announcements'
    | '/_society/society/approvals'
    | '/_society/society/bill-studio'
    | '/_society/society/billing'
    | '/_society/society/blocks'
    | '/_society/society/custom-fields'
    | '/_society/society/dashboard'
    | '/_society/society/digest'
    | '/_society/society/expenses'
    | '/_society/society/flats'
    | '/_society/society/leaderboard'
    | '/_society/society/ledger'
    | '/_society/society/maintenance'
    | '/_society/society/plan-required'
    | '/_society/society/polls'
    | '/_society/society/reports'
    | '/_society/society/residents'
    | '/_society/society/setup'
    | '/_society/society/team'
    | '/_society/society/vehicles'
    | '/_society/society/verifications'
    | '/_society/society/visitors'
    | '/_resident/app/feed/$postId'
    | '/api/public/hooks/run-billing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResidentRoute: typeof ResidentRouteWithChildren
  SocietyRoute: typeof SocietyRouteWithChildren
  GdprRoute: typeof GdprRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiSupportChatRoute: typeof ApiSupportChatRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  ApiPublicHooksRunBillingRoute: typeof ApiPublicHooksRunBillingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_society': {
      id: '/_society'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SocietyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resident': {
      id: '/_resident'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/plan': {
      id: '/onboarding/plan'
      path: '/plan'
      fullPath: '/onboarding/plan'
      preLoaderRoute: typeof OnboardingPlanRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/pending': {
      id: '/onboarding/pending'
      path: '/pending'
      fullPath: '/onboarding/pending'
      preLoaderRoute: typeof OnboardingPendingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/join': {
      id: '/onboarding/join'
      path: '/join'
      fullPath: '/onboarding/join'
      preLoaderRoute: typeof OnboardingJoinRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/create': {
      id: '/onboarding/create'
      path: '/create'
      fullPath: '/onboarding/create'
      preLoaderRoute: typeof OnboardingCreateRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support-chat': {
      id: '/api/support-chat'
      path: '/api/support-chat'
      fullPath: '/api/support-chat'
      preLoaderRoute: typeof ApiSupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/phone-otp': {
      id: '/_auth/phone-otp'
      path: '/phone-otp'
      fullPath: '/phone-otp'
      preLoaderRoute: typeof AuthPhoneOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_society/society/visitors': {
      id: '/_society/society/visitors'
      path: '/society/visitors'
      fullPath: '/society/visitors'
      preLoaderRoute: typeof SocietySocietyVisitorsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/verifications': {
      id: '/_society/society/verifications'
      path: '/society/verifications'
      fullPath: '/society/verifications'
      preLoaderRoute: typeof SocietySocietyVerificationsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/vehicles': {
      id: '/_society/society/vehicles'
      path: '/society/vehicles'
      fullPath: '/society/vehicles'
      preLoaderRoute: typeof SocietySocietyVehiclesRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/team': {
      id: '/_society/society/team'
      path: '/society/team'
      fullPath: '/society/team'
      preLoaderRoute: typeof SocietySocietyTeamRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/setup': {
      id: '/_society/society/setup'
      path: '/society/setup'
      fullPath: '/society/setup'
      preLoaderRoute: typeof SocietySocietySetupRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/residents': {
      id: '/_society/society/residents'
      path: '/society/residents'
      fullPath: '/society/residents'
      preLoaderRoute: typeof SocietySocietyResidentsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/reports': {
      id: '/_society/society/reports'
      path: '/society/reports'
      fullPath: '/society/reports'
      preLoaderRoute: typeof SocietySocietyReportsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/polls': {
      id: '/_society/society/polls'
      path: '/society/polls'
      fullPath: '/society/polls'
      preLoaderRoute: typeof SocietySocietyPollsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/plan-required': {
      id: '/_society/society/plan-required'
      path: '/society/plan-required'
      fullPath: '/society/plan-required'
      preLoaderRoute: typeof SocietySocietyPlanRequiredRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/maintenance': {
      id: '/_society/society/maintenance'
      path: '/society/maintenance'
      fullPath: '/society/maintenance'
      preLoaderRoute: typeof SocietySocietyMaintenanceRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/ledger': {
      id: '/_society/society/ledger'
      path: '/society/ledger'
      fullPath: '/society/ledger'
      preLoaderRoute: typeof SocietySocietyLedgerRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/leaderboard': {
      id: '/_society/society/leaderboard'
      path: '/society/leaderboard'
      fullPath: '/society/leaderboard'
      preLoaderRoute: typeof SocietySocietyLeaderboardRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/flats': {
      id: '/_society/society/flats'
      path: '/society/flats'
      fullPath: '/society/flats'
      preLoaderRoute: typeof SocietySocietyFlatsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/expenses': {
      id: '/_society/society/expenses'
      path: '/society/expenses'
      fullPath: '/society/expenses'
      preLoaderRoute: typeof SocietySocietyExpensesRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/digest': {
      id: '/_society/society/digest'
      path: '/society/digest'
      fullPath: '/society/digest'
      preLoaderRoute: typeof SocietySocietyDigestRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/dashboard': {
      id: '/_society/society/dashboard'
      path: '/society/dashboard'
      fullPath: '/society/dashboard'
      preLoaderRoute: typeof SocietySocietyDashboardRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/custom-fields': {
      id: '/_society/society/custom-fields'
      path: '/society/custom-fields'
      fullPath: '/society/custom-fields'
      preLoaderRoute: typeof SocietySocietyCustomFieldsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/blocks': {
      id: '/_society/society/blocks'
      path: '/society/blocks'
      fullPath: '/society/blocks'
      preLoaderRoute: typeof SocietySocietyBlocksRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/billing': {
      id: '/_society/society/billing'
      path: '/society/billing'
      fullPath: '/society/billing'
      preLoaderRoute: typeof SocietySocietyBillingRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/bill-studio': {
      id: '/_society/society/bill-studio'
      path: '/society/bill-studio'
      fullPath: '/society/bill-studio'
      preLoaderRoute: typeof SocietySocietyBillStudioRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/approvals': {
      id: '/_society/society/approvals'
      path: '/society/approvals'
      fullPath: '/society/approvals'
      preLoaderRoute: typeof SocietySocietyApprovalsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/announcements': {
      id: '/_society/society/announcements'
      path: '/society/announcements'
      fullPath: '/society/announcements'
      preLoaderRoute: typeof SocietySocietyAnnouncementsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_resident/app/visitors': {
      id: '/_resident/app/visitors'
      path: '/app/visitors'
      fullPath: '/app/visitors'
      preLoaderRoute: typeof ResidentAppVisitorsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/vehicles': {
      id: '/_resident/app/vehicles'
      path: '/app/vehicles'
      fullPath: '/app/vehicles'
      preLoaderRoute: typeof ResidentAppVehiclesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/trust': {
      id: '/_resident/app/trust'
      path: '/app/trust'
      fullPath: '/app/trust'
      preLoaderRoute: typeof ResidentAppTrustRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/services': {
      id: '/_resident/app/services'
      path: '/app/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof ResidentAppServicesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/profile': {
      id: '/_resident/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof ResidentAppProfileRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/polls': {
      id: '/_resident/app/polls'
      path: '/app/polls'
      fullPath: '/app/polls'
      preLoaderRoute: typeof ResidentAppPollsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/plan-required': {
      id: '/_resident/app/plan-required'
      path: '/app/plan-required'
      fullPath: '/app/plan-required'
      preLoaderRoute: typeof ResidentAppPlanRequiredRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/notices': {
      id: '/_resident/app/notices'
      path: '/app/notices'
      fullPath: '/app/notices'
      preLoaderRoute: typeof ResidentAppNoticesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/ledger': {
      id: '/_resident/app/ledger'
      path: '/app/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof ResidentAppLedgerRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/helpdesk': {
      id: '/_resident/app/helpdesk'
      path: '/app/helpdesk'
      fullPath: '/app/helpdesk'
      preLoaderRoute: typeof ResidentAppHelpdeskRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/guard': {
      id: '/_resident/app/guard'
      path: '/app/guard'
      fullPath: '/app/guard'
      preLoaderRoute: typeof ResidentAppGuardRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/feed': {
      id: '/_resident/app/feed'
      path: '/app/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof ResidentAppFeedRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/family': {
      id: '/_resident/app/family'
      path: '/app/family'
      fullPath: '/app/family'
      preLoaderRoute: typeof ResidentAppFamilyRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/emergency': {
      id: '/_resident/app/emergency'
      path: '/app/emergency'
      fullPath: '/app/emergency'
      preLoaderRoute: typeof ResidentAppEmergencyRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/dues': {
      id: '/_resident/app/dues'
      path: '/app/dues'
      fullPath: '/app/dues'
      preLoaderRoute: typeof ResidentAppDuesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/dashboard': {
      id: '/_resident/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof ResidentAppDashboardRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/bills': {
      id: '/_resident/app/bills'
      path: '/app/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof ResidentAppBillsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/activity': {
      id: '/_resident/app/activity'
      path: '/app/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof ResidentAppActivityRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/achievements': {
      id: '/_resident/app/achievements'
      path: '/app/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof ResidentAppAchievementsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_admin/admin/withdrawals': {
      id: '/_admin/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminAdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/razorpay': {
      id: '/_admin/admin/razorpay'
      path: '/admin/razorpay'
      fullPath: '/admin/razorpay'
      preLoaderRoute: typeof AdminAdminRazorpayRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/plans': {
      id: '/_admin/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminAdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/income': {
      id: '/_admin/admin/income'
      path: '/admin/income'
      fullPath: '/admin/income'
      preLoaderRoute: typeof AdminAdminIncomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/ads': {
      id: '/_admin/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/run-billing': {
      id: '/api/public/hooks/run-billing'
      path: '/api/public/hooks/run-billing'
      fullPath: '/api/public/hooks/run-billing'
      preLoaderRoute: typeof ApiPublicHooksRunBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resident/app/feed/$postId': {
      id: '/_resident/app/feed/$postId'
      path: '/$postId'
      fullPath: '/app/feed/$postId'
      preLoaderRoute: typeof ResidentAppFeedPostIdRouteImport
      parentRoute: typeof ResidentAppFeedRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAdsRoute: typeof AdminAdminAdsRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminIncomeRoute: typeof AdminAdminIncomeRoute
  AdminAdminPlansRoute: typeof AdminAdminPlansRoute
  AdminAdminRazorpayRoute: typeof AdminAdminRazorpayRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminWithdrawalsRoute: typeof AdminAdminWithdrawalsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAdsRoute: AdminAdminAdsRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminIncomeRoute: AdminAdminIncomeRoute,
  AdminAdminPlansRoute: AdminAdminPlansRoute,
  AdminAdminRazorpayRoute: AdminAdminRazorpayRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminWithdrawalsRoute: AdminAdminWithdrawalsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPhoneOtpRoute: typeof AuthPhoneOtpRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPhoneOtpRoute: AuthPhoneOtpRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ResidentAppFeedRouteChildren {
  ResidentAppFeedPostIdRoute: typeof ResidentAppFeedPostIdRoute
}

const ResidentAppFeedRouteChildren: ResidentAppFeedRouteChildren = {
  ResidentAppFeedPostIdRoute: ResidentAppFeedPostIdRoute,
}

const ResidentAppFeedRouteWithChildren = ResidentAppFeedRoute._addFileChildren(
  ResidentAppFeedRouteChildren,
)

interface ResidentRouteChildren {
  ResidentAppAchievementsRoute: typeof ResidentAppAchievementsRoute
  ResidentAppActivityRoute: typeof ResidentAppActivityRoute
  ResidentAppBillsRoute: typeof ResidentAppBillsRoute
  ResidentAppDashboardRoute: typeof ResidentAppDashboardRoute
  ResidentAppDuesRoute: typeof ResidentAppDuesRoute
  ResidentAppEmergencyRoute: typeof ResidentAppEmergencyRoute
  ResidentAppFamilyRoute: typeof ResidentAppFamilyRoute
  ResidentAppFeedRoute: typeof ResidentAppFeedRouteWithChildren
  ResidentAppGuardRoute: typeof ResidentAppGuardRoute
  ResidentAppHelpdeskRoute: typeof ResidentAppHelpdeskRoute
  ResidentAppLedgerRoute: typeof ResidentAppLedgerRoute
  ResidentAppNoticesRoute: typeof ResidentAppNoticesRoute
  ResidentAppPlanRequiredRoute: typeof ResidentAppPlanRequiredRoute
  ResidentAppPollsRoute: typeof ResidentAppPollsRoute
  ResidentAppProfileRoute: typeof ResidentAppProfileRoute
  ResidentAppServicesRoute: typeof ResidentAppServicesRoute
  ResidentAppTrustRoute: typeof ResidentAppTrustRoute
  ResidentAppVehiclesRoute: typeof ResidentAppVehiclesRoute
  ResidentAppVisitorsRoute: typeof ResidentAppVisitorsRoute
}

const ResidentRouteChildren: ResidentRouteChildren = {
  ResidentAppAchievementsRoute: ResidentAppAchievementsRoute,
  ResidentAppActivityRoute: ResidentAppActivityRoute,
  ResidentAppBillsRoute: ResidentAppBillsRoute,
  ResidentAppDashboardRoute: ResidentAppDashboardRoute,
  ResidentAppDuesRoute: ResidentAppDuesRoute,
  ResidentAppEmergencyRoute: ResidentAppEmergencyRoute,
  ResidentAppFamilyRoute: ResidentAppFamilyRoute,
  ResidentAppFeedRoute: ResidentAppFeedRouteWithChildren,
  ResidentAppGuardRoute: ResidentAppGuardRoute,
  ResidentAppHelpdeskRoute: ResidentAppHelpdeskRoute,
  ResidentAppLedgerRoute: ResidentAppLedgerRoute,
  ResidentAppNoticesRoute: ResidentAppNoticesRoute,
  ResidentAppPlanRequiredRoute: ResidentAppPlanRequiredRoute,
  ResidentAppPollsRoute: ResidentAppPollsRoute,
  ResidentAppProfileRoute: ResidentAppProfileRoute,
  ResidentAppServicesRoute: ResidentAppServicesRoute,
  ResidentAppTrustRoute: ResidentAppTrustRoute,
  ResidentAppVehiclesRoute: ResidentAppVehiclesRoute,
  ResidentAppVisitorsRoute: ResidentAppVisitorsRoute,
}

const ResidentRouteWithChildren = ResidentRoute._addFileChildren(
  ResidentRouteChildren,
)

interface SocietyRouteChildren {
  SocietySocietyAnnouncementsRoute: typeof SocietySocietyAnnouncementsRoute
  SocietySocietyApprovalsRoute: typeof SocietySocietyApprovalsRoute
  SocietySocietyBillStudioRoute: typeof SocietySocietyBillStudioRoute
  SocietySocietyBillingRoute: typeof SocietySocietyBillingRoute
  SocietySocietyBlocksRoute: typeof SocietySocietyBlocksRoute
  SocietySocietyCustomFieldsRoute: typeof SocietySocietyCustomFieldsRoute
  SocietySocietyDashboardRoute: typeof SocietySocietyDashboardRoute
  SocietySocietyDigestRoute: typeof SocietySocietyDigestRoute
  SocietySocietyExpensesRoute: typeof SocietySocietyExpensesRoute
  SocietySocietyFlatsRoute: typeof SocietySocietyFlatsRoute
  SocietySocietyLeaderboardRoute: typeof SocietySocietyLeaderboardRoute
  SocietySocietyLedgerRoute: typeof SocietySocietyLedgerRoute
  SocietySocietyMaintenanceRoute: typeof SocietySocietyMaintenanceRoute
  SocietySocietyPlanRequiredRoute: typeof SocietySocietyPlanRequiredRoute
  SocietySocietyPollsRoute: typeof SocietySocietyPollsRoute
  SocietySocietyReportsRoute: typeof SocietySocietyReportsRoute
  SocietySocietyResidentsRoute: typeof SocietySocietyResidentsRoute
  SocietySocietySetupRoute: typeof SocietySocietySetupRoute
  SocietySocietyTeamRoute: typeof SocietySocietyTeamRoute
  SocietySocietyVehiclesRoute: typeof SocietySocietyVehiclesRoute
  SocietySocietyVerificationsRoute: typeof SocietySocietyVerificationsRoute
  SocietySocietyVisitorsRoute: typeof SocietySocietyVisitorsRoute
}

const SocietyRouteChildren: SocietyRouteChildren = {
  SocietySocietyAnnouncementsRoute: SocietySocietyAnnouncementsRoute,
  SocietySocietyApprovalsRoute: SocietySocietyApprovalsRoute,
  SocietySocietyBillStudioRoute: SocietySocietyBillStudioRoute,
  SocietySocietyBillingRoute: SocietySocietyBillingRoute,
  SocietySocietyBlocksRoute: SocietySocietyBlocksRoute,
  SocietySocietyCustomFieldsRoute: SocietySocietyCustomFieldsRoute,
  SocietySocietyDashboardRoute: SocietySocietyDashboardRoute,
  SocietySocietyDigestRoute: SocietySocietyDigestRoute,
  SocietySocietyExpensesRoute: SocietySocietyExpensesRoute,
  SocietySocietyFlatsRoute: SocietySocietyFlatsRoute,
  SocietySocietyLeaderboardRoute: SocietySocietyLeaderboardRoute,
  SocietySocietyLedgerRoute: SocietySocietyLedgerRoute,
  SocietySocietyMaintenanceRoute: SocietySocietyMaintenanceRoute,
  SocietySocietyPlanRequiredRoute: SocietySocietyPlanRequiredRoute,
  SocietySocietyPollsRoute: SocietySocietyPollsRoute,
  SocietySocietyReportsRoute: SocietySocietyReportsRoute,
  SocietySocietyResidentsRoute: SocietySocietyResidentsRoute,
  SocietySocietySetupRoute: SocietySocietySetupRoute,
  SocietySocietyTeamRoute: SocietySocietyTeamRoute,
  SocietySocietyVehiclesRoute: SocietySocietyVehiclesRoute,
  SocietySocietyVerificationsRoute: SocietySocietyVerificationsRoute,
  SocietySocietyVisitorsRoute: SocietySocietyVisitorsRoute,
}

const SocietyRouteWithChildren =
  SocietyRoute._addFileChildren(SocietyRouteChildren)

interface OnboardingRouteChildren {
  OnboardingCreateRoute: typeof OnboardingCreateRoute
  OnboardingJoinRoute: typeof OnboardingJoinRoute
  OnboardingPendingRoute: typeof OnboardingPendingRoute
  OnboardingPlanRoute: typeof OnboardingPlanRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCreateRoute: OnboardingCreateRoute,
  OnboardingJoinRoute: OnboardingJoinRoute,
  OnboardingPendingRoute: OnboardingPendingRoute,
  OnboardingPlanRoute: OnboardingPlanRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResidentRoute: ResidentRouteWithChildren,
  SocietyRoute: SocietyRouteWithChildren,
  GdprRoute: GdprRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  ApiSupportChatRoute: ApiSupportChatRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  ApiPublicHooksRunBillingRoute: ApiPublicHooksRunBillingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
