/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SocietyRouteImport } from './routes/_society'
import { Route as ResidentRouteImport } from './routes/_resident'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as SocietySocietyResidentsRouteImport } from './routes/_society/society.residents'
import { Route as SocietySocietyFlatsRouteImport } from './routes/_society/society.flats'
import { Route as SocietySocietyDashboardRouteImport } from './routes/_society/society.dashboard'
import { Route as SocietySocietyBlocksRouteImport } from './routes/_society/society.blocks'
import { Route as ResidentAppProfileRouteImport } from './routes/_resident/app.profile'
import { Route as ResidentAppNoticesRouteImport } from './routes/_resident/app.notices'
import { Route as ResidentAppHelpdeskRouteImport } from './routes/_resident/app.helpdesk'
import { Route as ResidentAppDuesRouteImport } from './routes/_resident/app.dues'
import { Route as ResidentAppDashboardRouteImport } from './routes/_resident/app.dashboard'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin.dashboard'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietyRoute = SocietyRouteImport.update({
  id: '/_society',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentRoute = ResidentRouteImport.update({
  id: '/_resident',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const SocietySocietyResidentsRoute = SocietySocietyResidentsRouteImport.update({
  id: '/society/residents',
  path: '/society/residents',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyFlatsRoute = SocietySocietyFlatsRouteImport.update({
  id: '/society/flats',
  path: '/society/flats',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyDashboardRoute = SocietySocietyDashboardRouteImport.update({
  id: '/society/dashboard',
  path: '/society/dashboard',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyBlocksRoute = SocietySocietyBlocksRouteImport.update({
  id: '/society/blocks',
  path: '/society/blocks',
  getParentRoute: () => SocietyRoute,
} as any)
const ResidentAppProfileRoute = ResidentAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppNoticesRoute = ResidentAppNoticesRouteImport.update({
  id: '/app/notices',
  path: '/app/notices',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppHelpdeskRoute = ResidentAppHelpdeskRouteImport.update({
  id: '/app/helpdesk',
  path: '/app/helpdesk',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppDuesRoute = ResidentAppDuesRouteImport.update({
  id: '/app/dues',
  path: '/app/dues',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppDashboardRoute = ResidentAppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => ResidentRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/app/dashboard': typeof ResidentAppDashboardRoute
  '/app/dues': typeof ResidentAppDuesRoute
  '/app/helpdesk': typeof ResidentAppHelpdeskRoute
  '/app/notices': typeof ResidentAppNoticesRoute
  '/app/profile': typeof ResidentAppProfileRoute
  '/society/blocks': typeof SocietySocietyBlocksRoute
  '/society/dashboard': typeof SocietySocietyDashboardRoute
  '/society/flats': typeof SocietySocietyFlatsRoute
  '/society/residents': typeof SocietySocietyResidentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/app/dashboard': typeof ResidentAppDashboardRoute
  '/app/dues': typeof ResidentAppDuesRoute
  '/app/helpdesk': typeof ResidentAppHelpdeskRoute
  '/app/notices': typeof ResidentAppNoticesRoute
  '/app/profile': typeof ResidentAppProfileRoute
  '/society/blocks': typeof SocietySocietyBlocksRoute
  '/society/dashboard': typeof SocietySocietyDashboardRoute
  '/society/flats': typeof SocietySocietyFlatsRoute
  '/society/residents': typeof SocietySocietyResidentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_resident': typeof ResidentRouteWithChildren
  '/_society': typeof SocietyRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_resident/app/dashboard': typeof ResidentAppDashboardRoute
  '/_resident/app/dues': typeof ResidentAppDuesRoute
  '/_resident/app/helpdesk': typeof ResidentAppHelpdeskRoute
  '/_resident/app/notices': typeof ResidentAppNoticesRoute
  '/_resident/app/profile': typeof ResidentAppProfileRoute
  '/_society/society/blocks': typeof SocietySocietyBlocksRoute
  '/_society/society/dashboard': typeof SocietySocietyDashboardRoute
  '/_society/society/flats': typeof SocietySocietyFlatsRoute
  '/_society/society/residents': typeof SocietySocietyResidentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/dashboard'
    | '/app/dashboard'
    | '/app/dues'
    | '/app/helpdesk'
    | '/app/notices'
    | '/app/profile'
    | '/society/blocks'
    | '/society/dashboard'
    | '/society/flats'
    | '/society/residents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/dashboard'
    | '/app/dashboard'
    | '/app/dues'
    | '/app/helpdesk'
    | '/app/notices'
    | '/app/profile'
    | '/society/blocks'
    | '/society/dashboard'
    | '/society/flats'
    | '/society/residents'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_resident'
    | '/_society'
    | '/onboarding'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_admin/admin/dashboard'
    | '/_resident/app/dashboard'
    | '/_resident/app/dues'
    | '/_resident/app/helpdesk'
    | '/_resident/app/notices'
    | '/_resident/app/profile'
    | '/_society/society/blocks'
    | '/_society/society/dashboard'
    | '/_society/society/flats'
    | '/_society/society/residents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResidentRoute: typeof ResidentRouteWithChildren
  SocietyRoute: typeof SocietyRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_society': {
      id: '/_society'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SocietyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resident': {
      id: '/_resident'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_society/society/residents': {
      id: '/_society/society/residents'
      path: '/society/residents'
      fullPath: '/society/residents'
      preLoaderRoute: typeof SocietySocietyResidentsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/flats': {
      id: '/_society/society/flats'
      path: '/society/flats'
      fullPath: '/society/flats'
      preLoaderRoute: typeof SocietySocietyFlatsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/dashboard': {
      id: '/_society/society/dashboard'
      path: '/society/dashboard'
      fullPath: '/society/dashboard'
      preLoaderRoute: typeof SocietySocietyDashboardRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/blocks': {
      id: '/_society/society/blocks'
      path: '/society/blocks'
      fullPath: '/society/blocks'
      preLoaderRoute: typeof SocietySocietyBlocksRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_resident/app/profile': {
      id: '/_resident/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof ResidentAppProfileRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/notices': {
      id: '/_resident/app/notices'
      path: '/app/notices'
      fullPath: '/app/notices'
      preLoaderRoute: typeof ResidentAppNoticesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/helpdesk': {
      id: '/_resident/app/helpdesk'
      path: '/app/helpdesk'
      fullPath: '/app/helpdesk'
      preLoaderRoute: typeof ResidentAppHelpdeskRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/dues': {
      id: '/_resident/app/dues'
      path: '/app/dues'
      fullPath: '/app/dues'
      preLoaderRoute: typeof ResidentAppDuesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/dashboard': {
      id: '/_resident/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof ResidentAppDashboardRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ResidentRouteChildren {
  ResidentAppDashboardRoute: typeof ResidentAppDashboardRoute
  ResidentAppDuesRoute: typeof ResidentAppDuesRoute
  ResidentAppHelpdeskRoute: typeof ResidentAppHelpdeskRoute
  ResidentAppNoticesRoute: typeof ResidentAppNoticesRoute
  ResidentAppProfileRoute: typeof ResidentAppProfileRoute
}

const ResidentRouteChildren: ResidentRouteChildren = {
  ResidentAppDashboardRoute: ResidentAppDashboardRoute,
  ResidentAppDuesRoute: ResidentAppDuesRoute,
  ResidentAppHelpdeskRoute: ResidentAppHelpdeskRoute,
  ResidentAppNoticesRoute: ResidentAppNoticesRoute,
  ResidentAppProfileRoute: ResidentAppProfileRoute,
}

const ResidentRouteWithChildren = ResidentRoute._addFileChildren(
  ResidentRouteChildren,
)

interface SocietyRouteChildren {
  SocietySocietyBlocksRoute: typeof SocietySocietyBlocksRoute
  SocietySocietyDashboardRoute: typeof SocietySocietyDashboardRoute
  SocietySocietyFlatsRoute: typeof SocietySocietyFlatsRoute
  SocietySocietyResidentsRoute: typeof SocietySocietyResidentsRoute
}

const SocietyRouteChildren: SocietyRouteChildren = {
  SocietySocietyBlocksRoute: SocietySocietyBlocksRoute,
  SocietySocietyDashboardRoute: SocietySocietyDashboardRoute,
  SocietySocietyFlatsRoute: SocietySocietyFlatsRoute,
  SocietySocietyResidentsRoute: SocietySocietyResidentsRoute,
}

const SocietyRouteWithChildren =
  SocietyRoute._addFileChildren(SocietyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResidentRoute: ResidentRouteWithChildren,
  SocietyRoute: SocietyRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
