/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SocietyRouteImport } from './routes/_society'
import { Route as ResidentRouteImport } from './routes/_resident'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingJoinRouteImport } from './routes/onboarding.join'
import { Route as OnboardingCreateRouteImport } from './routes/onboarding.create'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as SocietySocietyTeamRouteImport } from './routes/_society/society.team'
import { Route as SocietySocietyResidentsRouteImport } from './routes/_society/society.residents'
import { Route as SocietySocietyPollsRouteImport } from './routes/_society/society.polls'
import { Route as SocietySocietyLedgerRouteImport } from './routes/_society/society.ledger'
import { Route as SocietySocietyFlatsRouteImport } from './routes/_society/society.flats'
import { Route as SocietySocietyDigestRouteImport } from './routes/_society/society.digest'
import { Route as SocietySocietyDashboardRouteImport } from './routes/_society/society.dashboard'
import { Route as SocietySocietyBlocksRouteImport } from './routes/_society/society.blocks'
import { Route as ResidentAppVisitorsRouteImport } from './routes/_resident/app.visitors'
import { Route as ResidentAppVehiclesRouteImport } from './routes/_resident/app.vehicles'
import { Route as ResidentAppTrustRouteImport } from './routes/_resident/app.trust'
import { Route as ResidentAppServicesRouteImport } from './routes/_resident/app.services'
import { Route as ResidentAppProfileRouteImport } from './routes/_resident/app.profile'
import { Route as ResidentAppPollsRouteImport } from './routes/_resident/app.polls'
import { Route as ResidentAppNoticesRouteImport } from './routes/_resident/app.notices'
import { Route as ResidentAppLedgerRouteImport } from './routes/_resident/app.ledger'
import { Route as ResidentAppHelpdeskRouteImport } from './routes/_resident/app.helpdesk'
import { Route as ResidentAppGuardRouteImport } from './routes/_resident/app.guard'
import { Route as ResidentAppFeedRouteImport } from './routes/_resident/app.feed'
import { Route as ResidentAppDuesRouteImport } from './routes/_resident/app.dues'
import { Route as ResidentAppDashboardRouteImport } from './routes/_resident/app.dashboard'
import { Route as ResidentAppBillsRouteImport } from './routes/_resident/app.bills'
import { Route as ResidentAppActivityRouteImport } from './routes/_resident/app.activity'
import { Route as ResidentAppAchievementsRouteImport } from './routes/_resident/app.achievements'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin.dashboard'
import { Route as ResidentAppFeedPostIdRouteImport } from './routes/_resident/app.feed.$postId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietyRoute = SocietyRouteImport.update({
  id: '/_society',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentRoute = ResidentRouteImport.update({
  id: '/_resident',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingJoinRoute = OnboardingJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCreateRoute = OnboardingCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const SocietySocietyTeamRoute = SocietySocietyTeamRouteImport.update({
  id: '/society/team',
  path: '/society/team',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyResidentsRoute = SocietySocietyResidentsRouteImport.update({
  id: '/society/residents',
  path: '/society/residents',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyPollsRoute = SocietySocietyPollsRouteImport.update({
  id: '/society/polls',
  path: '/society/polls',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyLedgerRoute = SocietySocietyLedgerRouteImport.update({
  id: '/society/ledger',
  path: '/society/ledger',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyFlatsRoute = SocietySocietyFlatsRouteImport.update({
  id: '/society/flats',
  path: '/society/flats',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyDigestRoute = SocietySocietyDigestRouteImport.update({
  id: '/society/digest',
  path: '/society/digest',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyDashboardRoute = SocietySocietyDashboardRouteImport.update({
  id: '/society/dashboard',
  path: '/society/dashboard',
  getParentRoute: () => SocietyRoute,
} as any)
const SocietySocietyBlocksRoute = SocietySocietyBlocksRouteImport.update({
  id: '/society/blocks',
  path: '/society/blocks',
  getParentRoute: () => SocietyRoute,
} as any)
const ResidentAppVisitorsRoute = ResidentAppVisitorsRouteImport.update({
  id: '/app/visitors',
  path: '/app/visitors',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppVehiclesRoute = ResidentAppVehiclesRouteImport.update({
  id: '/app/vehicles',
  path: '/app/vehicles',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppTrustRoute = ResidentAppTrustRouteImport.update({
  id: '/app/trust',
  path: '/app/trust',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppServicesRoute = ResidentAppServicesRouteImport.update({
  id: '/app/services',
  path: '/app/services',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppProfileRoute = ResidentAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppPollsRoute = ResidentAppPollsRouteImport.update({
  id: '/app/polls',
  path: '/app/polls',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppNoticesRoute = ResidentAppNoticesRouteImport.update({
  id: '/app/notices',
  path: '/app/notices',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppLedgerRoute = ResidentAppLedgerRouteImport.update({
  id: '/app/ledger',
  path: '/app/ledger',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppHelpdeskRoute = ResidentAppHelpdeskRouteImport.update({
  id: '/app/helpdesk',
  path: '/app/helpdesk',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppGuardRoute = ResidentAppGuardRouteImport.update({
  id: '/app/guard',
  path: '/app/guard',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppFeedRoute = ResidentAppFeedRouteImport.update({
  id: '/app/feed',
  path: '/app/feed',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppDuesRoute = ResidentAppDuesRouteImport.update({
  id: '/app/dues',
  path: '/app/dues',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppDashboardRoute = ResidentAppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppBillsRoute = ResidentAppBillsRouteImport.update({
  id: '/app/bills',
  path: '/app/bills',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppActivityRoute = ResidentAppActivityRouteImport.update({
  id: '/app/activity',
  path: '/app/activity',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentAppAchievementsRoute = ResidentAppAchievementsRouteImport.update({
  id: '/app/achievements',
  path: '/app/achievements',
  getParentRoute: () => ResidentRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ResidentAppFeedPostIdRoute = ResidentAppFeedPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => ResidentAppFeedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/terms': typeof TermsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/onboarding/create': typeof OnboardingCreateRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/app/achievements': typeof ResidentAppAchievementsRoute
  '/app/activity': typeof ResidentAppActivityRoute
  '/app/bills': typeof ResidentAppBillsRoute
  '/app/dashboard': typeof ResidentAppDashboardRoute
  '/app/dues': typeof ResidentAppDuesRoute
  '/app/feed': typeof ResidentAppFeedRouteWithChildren
  '/app/guard': typeof ResidentAppGuardRoute
  '/app/helpdesk': typeof ResidentAppHelpdeskRoute
  '/app/ledger': typeof ResidentAppLedgerRoute
  '/app/notices': typeof ResidentAppNoticesRoute
  '/app/polls': typeof ResidentAppPollsRoute
  '/app/profile': typeof ResidentAppProfileRoute
  '/app/services': typeof ResidentAppServicesRoute
  '/app/trust': typeof ResidentAppTrustRoute
  '/app/vehicles': typeof ResidentAppVehiclesRoute
  '/app/visitors': typeof ResidentAppVisitorsRoute
  '/society/blocks': typeof SocietySocietyBlocksRoute
  '/society/dashboard': typeof SocietySocietyDashboardRoute
  '/society/digest': typeof SocietySocietyDigestRoute
  '/society/flats': typeof SocietySocietyFlatsRoute
  '/society/ledger': typeof SocietySocietyLedgerRoute
  '/society/polls': typeof SocietySocietyPollsRoute
  '/society/residents': typeof SocietySocietyResidentsRoute
  '/society/team': typeof SocietySocietyTeamRoute
  '/app/feed/$postId': typeof ResidentAppFeedPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/onboarding/create': typeof OnboardingCreateRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/app/achievements': typeof ResidentAppAchievementsRoute
  '/app/activity': typeof ResidentAppActivityRoute
  '/app/bills': typeof ResidentAppBillsRoute
  '/app/dashboard': typeof ResidentAppDashboardRoute
  '/app/dues': typeof ResidentAppDuesRoute
  '/app/feed': typeof ResidentAppFeedRouteWithChildren
  '/app/guard': typeof ResidentAppGuardRoute
  '/app/helpdesk': typeof ResidentAppHelpdeskRoute
  '/app/ledger': typeof ResidentAppLedgerRoute
  '/app/notices': typeof ResidentAppNoticesRoute
  '/app/polls': typeof ResidentAppPollsRoute
  '/app/profile': typeof ResidentAppProfileRoute
  '/app/services': typeof ResidentAppServicesRoute
  '/app/trust': typeof ResidentAppTrustRoute
  '/app/vehicles': typeof ResidentAppVehiclesRoute
  '/app/visitors': typeof ResidentAppVisitorsRoute
  '/society/blocks': typeof SocietySocietyBlocksRoute
  '/society/dashboard': typeof SocietySocietyDashboardRoute
  '/society/digest': typeof SocietySocietyDigestRoute
  '/society/flats': typeof SocietySocietyFlatsRoute
  '/society/ledger': typeof SocietySocietyLedgerRoute
  '/society/polls': typeof SocietySocietyPollsRoute
  '/society/residents': typeof SocietySocietyResidentsRoute
  '/society/team': typeof SocietySocietyTeamRoute
  '/app/feed/$postId': typeof ResidentAppFeedPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_resident': typeof ResidentRouteWithChildren
  '/_society': typeof SocietyRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/terms': typeof TermsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/onboarding/create': typeof OnboardingCreateRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_resident/app/achievements': typeof ResidentAppAchievementsRoute
  '/_resident/app/activity': typeof ResidentAppActivityRoute
  '/_resident/app/bills': typeof ResidentAppBillsRoute
  '/_resident/app/dashboard': typeof ResidentAppDashboardRoute
  '/_resident/app/dues': typeof ResidentAppDuesRoute
  '/_resident/app/feed': typeof ResidentAppFeedRouteWithChildren
  '/_resident/app/guard': typeof ResidentAppGuardRoute
  '/_resident/app/helpdesk': typeof ResidentAppHelpdeskRoute
  '/_resident/app/ledger': typeof ResidentAppLedgerRoute
  '/_resident/app/notices': typeof ResidentAppNoticesRoute
  '/_resident/app/polls': typeof ResidentAppPollsRoute
  '/_resident/app/profile': typeof ResidentAppProfileRoute
  '/_resident/app/services': typeof ResidentAppServicesRoute
  '/_resident/app/trust': typeof ResidentAppTrustRoute
  '/_resident/app/vehicles': typeof ResidentAppVehiclesRoute
  '/_resident/app/visitors': typeof ResidentAppVisitorsRoute
  '/_society/society/blocks': typeof SocietySocietyBlocksRoute
  '/_society/society/dashboard': typeof SocietySocietyDashboardRoute
  '/_society/society/digest': typeof SocietySocietyDigestRoute
  '/_society/society/flats': typeof SocietySocietyFlatsRoute
  '/_society/society/ledger': typeof SocietySocietyLedgerRoute
  '/_society/society/polls': typeof SocietySocietyPollsRoute
  '/_society/society/residents': typeof SocietySocietyResidentsRoute
  '/_society/society/team': typeof SocietySocietyTeamRoute
  '/_resident/app/feed/$postId': typeof ResidentAppFeedPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/terms'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/onboarding/create'
    | '/onboarding/join'
    | '/onboarding/'
    | '/admin/dashboard'
    | '/app/achievements'
    | '/app/activity'
    | '/app/bills'
    | '/app/dashboard'
    | '/app/dues'
    | '/app/feed'
    | '/app/guard'
    | '/app/helpdesk'
    | '/app/ledger'
    | '/app/notices'
    | '/app/polls'
    | '/app/profile'
    | '/app/services'
    | '/app/trust'
    | '/app/vehicles'
    | '/app/visitors'
    | '/society/blocks'
    | '/society/dashboard'
    | '/society/digest'
    | '/society/flats'
    | '/society/ledger'
    | '/society/polls'
    | '/society/residents'
    | '/society/team'
    | '/app/feed/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terms'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/onboarding/create'
    | '/onboarding/join'
    | '/onboarding'
    | '/admin/dashboard'
    | '/app/achievements'
    | '/app/activity'
    | '/app/bills'
    | '/app/dashboard'
    | '/app/dues'
    | '/app/feed'
    | '/app/guard'
    | '/app/helpdesk'
    | '/app/ledger'
    | '/app/notices'
    | '/app/polls'
    | '/app/profile'
    | '/app/services'
    | '/app/trust'
    | '/app/vehicles'
    | '/app/visitors'
    | '/society/blocks'
    | '/society/dashboard'
    | '/society/digest'
    | '/society/flats'
    | '/society/ledger'
    | '/society/polls'
    | '/society/residents'
    | '/society/team'
    | '/app/feed/$postId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_resident'
    | '/_society'
    | '/onboarding'
    | '/terms'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/onboarding/create'
    | '/onboarding/join'
    | '/onboarding/'
    | '/_admin/admin/dashboard'
    | '/_resident/app/achievements'
    | '/_resident/app/activity'
    | '/_resident/app/bills'
    | '/_resident/app/dashboard'
    | '/_resident/app/dues'
    | '/_resident/app/feed'
    | '/_resident/app/guard'
    | '/_resident/app/helpdesk'
    | '/_resident/app/ledger'
    | '/_resident/app/notices'
    | '/_resident/app/polls'
    | '/_resident/app/profile'
    | '/_resident/app/services'
    | '/_resident/app/trust'
    | '/_resident/app/vehicles'
    | '/_resident/app/visitors'
    | '/_society/society/blocks'
    | '/_society/society/dashboard'
    | '/_society/society/digest'
    | '/_society/society/flats'
    | '/_society/society/ledger'
    | '/_society/society/polls'
    | '/_society/society/residents'
    | '/_society/society/team'
    | '/_resident/app/feed/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResidentRoute: typeof ResidentRouteWithChildren
  SocietyRoute: typeof SocietyRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_society': {
      id: '/_society'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SocietyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resident': {
      id: '/_resident'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/join': {
      id: '/onboarding/join'
      path: '/join'
      fullPath: '/onboarding/join'
      preLoaderRoute: typeof OnboardingJoinRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/create': {
      id: '/onboarding/create'
      path: '/create'
      fullPath: '/onboarding/create'
      preLoaderRoute: typeof OnboardingCreateRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_society/society/team': {
      id: '/_society/society/team'
      path: '/society/team'
      fullPath: '/society/team'
      preLoaderRoute: typeof SocietySocietyTeamRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/residents': {
      id: '/_society/society/residents'
      path: '/society/residents'
      fullPath: '/society/residents'
      preLoaderRoute: typeof SocietySocietyResidentsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/polls': {
      id: '/_society/society/polls'
      path: '/society/polls'
      fullPath: '/society/polls'
      preLoaderRoute: typeof SocietySocietyPollsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/ledger': {
      id: '/_society/society/ledger'
      path: '/society/ledger'
      fullPath: '/society/ledger'
      preLoaderRoute: typeof SocietySocietyLedgerRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/flats': {
      id: '/_society/society/flats'
      path: '/society/flats'
      fullPath: '/society/flats'
      preLoaderRoute: typeof SocietySocietyFlatsRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/digest': {
      id: '/_society/society/digest'
      path: '/society/digest'
      fullPath: '/society/digest'
      preLoaderRoute: typeof SocietySocietyDigestRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/dashboard': {
      id: '/_society/society/dashboard'
      path: '/society/dashboard'
      fullPath: '/society/dashboard'
      preLoaderRoute: typeof SocietySocietyDashboardRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_society/society/blocks': {
      id: '/_society/society/blocks'
      path: '/society/blocks'
      fullPath: '/society/blocks'
      preLoaderRoute: typeof SocietySocietyBlocksRouteImport
      parentRoute: typeof SocietyRoute
    }
    '/_resident/app/visitors': {
      id: '/_resident/app/visitors'
      path: '/app/visitors'
      fullPath: '/app/visitors'
      preLoaderRoute: typeof ResidentAppVisitorsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/vehicles': {
      id: '/_resident/app/vehicles'
      path: '/app/vehicles'
      fullPath: '/app/vehicles'
      preLoaderRoute: typeof ResidentAppVehiclesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/trust': {
      id: '/_resident/app/trust'
      path: '/app/trust'
      fullPath: '/app/trust'
      preLoaderRoute: typeof ResidentAppTrustRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/services': {
      id: '/_resident/app/services'
      path: '/app/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof ResidentAppServicesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/profile': {
      id: '/_resident/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof ResidentAppProfileRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/polls': {
      id: '/_resident/app/polls'
      path: '/app/polls'
      fullPath: '/app/polls'
      preLoaderRoute: typeof ResidentAppPollsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/notices': {
      id: '/_resident/app/notices'
      path: '/app/notices'
      fullPath: '/app/notices'
      preLoaderRoute: typeof ResidentAppNoticesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/ledger': {
      id: '/_resident/app/ledger'
      path: '/app/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof ResidentAppLedgerRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/helpdesk': {
      id: '/_resident/app/helpdesk'
      path: '/app/helpdesk'
      fullPath: '/app/helpdesk'
      preLoaderRoute: typeof ResidentAppHelpdeskRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/guard': {
      id: '/_resident/app/guard'
      path: '/app/guard'
      fullPath: '/app/guard'
      preLoaderRoute: typeof ResidentAppGuardRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/feed': {
      id: '/_resident/app/feed'
      path: '/app/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof ResidentAppFeedRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/dues': {
      id: '/_resident/app/dues'
      path: '/app/dues'
      fullPath: '/app/dues'
      preLoaderRoute: typeof ResidentAppDuesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/dashboard': {
      id: '/_resident/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof ResidentAppDashboardRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/bills': {
      id: '/_resident/app/bills'
      path: '/app/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof ResidentAppBillsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/activity': {
      id: '/_resident/app/activity'
      path: '/app/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof ResidentAppActivityRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_resident/app/achievements': {
      id: '/_resident/app/achievements'
      path: '/app/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof ResidentAppAchievementsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_resident/app/feed/$postId': {
      id: '/_resident/app/feed/$postId'
      path: '/$postId'
      fullPath: '/app/feed/$postId'
      preLoaderRoute: typeof ResidentAppFeedPostIdRouteImport
      parentRoute: typeof ResidentAppFeedRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ResidentAppFeedRouteChildren {
  ResidentAppFeedPostIdRoute: typeof ResidentAppFeedPostIdRoute
}

const ResidentAppFeedRouteChildren: ResidentAppFeedRouteChildren = {
  ResidentAppFeedPostIdRoute: ResidentAppFeedPostIdRoute,
}

const ResidentAppFeedRouteWithChildren = ResidentAppFeedRoute._addFileChildren(
  ResidentAppFeedRouteChildren,
)

interface ResidentRouteChildren {
  ResidentAppAchievementsRoute: typeof ResidentAppAchievementsRoute
  ResidentAppActivityRoute: typeof ResidentAppActivityRoute
  ResidentAppBillsRoute: typeof ResidentAppBillsRoute
  ResidentAppDashboardRoute: typeof ResidentAppDashboardRoute
  ResidentAppDuesRoute: typeof ResidentAppDuesRoute
  ResidentAppFeedRoute: typeof ResidentAppFeedRouteWithChildren
  ResidentAppGuardRoute: typeof ResidentAppGuardRoute
  ResidentAppHelpdeskRoute: typeof ResidentAppHelpdeskRoute
  ResidentAppLedgerRoute: typeof ResidentAppLedgerRoute
  ResidentAppNoticesRoute: typeof ResidentAppNoticesRoute
  ResidentAppPollsRoute: typeof ResidentAppPollsRoute
  ResidentAppProfileRoute: typeof ResidentAppProfileRoute
  ResidentAppServicesRoute: typeof ResidentAppServicesRoute
  ResidentAppTrustRoute: typeof ResidentAppTrustRoute
  ResidentAppVehiclesRoute: typeof ResidentAppVehiclesRoute
  ResidentAppVisitorsRoute: typeof ResidentAppVisitorsRoute
}

const ResidentRouteChildren: ResidentRouteChildren = {
  ResidentAppAchievementsRoute: ResidentAppAchievementsRoute,
  ResidentAppActivityRoute: ResidentAppActivityRoute,
  ResidentAppBillsRoute: ResidentAppBillsRoute,
  ResidentAppDashboardRoute: ResidentAppDashboardRoute,
  ResidentAppDuesRoute: ResidentAppDuesRoute,
  ResidentAppFeedRoute: ResidentAppFeedRouteWithChildren,
  ResidentAppGuardRoute: ResidentAppGuardRoute,
  ResidentAppHelpdeskRoute: ResidentAppHelpdeskRoute,
  ResidentAppLedgerRoute: ResidentAppLedgerRoute,
  ResidentAppNoticesRoute: ResidentAppNoticesRoute,
  ResidentAppPollsRoute: ResidentAppPollsRoute,
  ResidentAppProfileRoute: ResidentAppProfileRoute,
  ResidentAppServicesRoute: ResidentAppServicesRoute,
  ResidentAppTrustRoute: ResidentAppTrustRoute,
  ResidentAppVehiclesRoute: ResidentAppVehiclesRoute,
  ResidentAppVisitorsRoute: ResidentAppVisitorsRoute,
}

const ResidentRouteWithChildren = ResidentRoute._addFileChildren(
  ResidentRouteChildren,
)

interface SocietyRouteChildren {
  SocietySocietyBlocksRoute: typeof SocietySocietyBlocksRoute
  SocietySocietyDashboardRoute: typeof SocietySocietyDashboardRoute
  SocietySocietyDigestRoute: typeof SocietySocietyDigestRoute
  SocietySocietyFlatsRoute: typeof SocietySocietyFlatsRoute
  SocietySocietyLedgerRoute: typeof SocietySocietyLedgerRoute
  SocietySocietyPollsRoute: typeof SocietySocietyPollsRoute
  SocietySocietyResidentsRoute: typeof SocietySocietyResidentsRoute
  SocietySocietyTeamRoute: typeof SocietySocietyTeamRoute
}

const SocietyRouteChildren: SocietyRouteChildren = {
  SocietySocietyBlocksRoute: SocietySocietyBlocksRoute,
  SocietySocietyDashboardRoute: SocietySocietyDashboardRoute,
  SocietySocietyDigestRoute: SocietySocietyDigestRoute,
  SocietySocietyFlatsRoute: SocietySocietyFlatsRoute,
  SocietySocietyLedgerRoute: SocietySocietyLedgerRoute,
  SocietySocietyPollsRoute: SocietySocietyPollsRoute,
  SocietySocietyResidentsRoute: SocietySocietyResidentsRoute,
  SocietySocietyTeamRoute: SocietySocietyTeamRoute,
}

const SocietyRouteWithChildren =
  SocietyRoute._addFileChildren(SocietyRouteChildren)

interface OnboardingRouteChildren {
  OnboardingCreateRoute: typeof OnboardingCreateRoute
  OnboardingJoinRoute: typeof OnboardingJoinRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCreateRoute: OnboardingCreateRoute,
  OnboardingJoinRoute: OnboardingJoinRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResidentRoute: ResidentRouteWithChildren,
  SocietyRoute: SocietyRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
