REVOKE EXECUTE ON FUNCTION public._allocate_receipt_number(uuid, timestamptz) FROM anon;
REVOKE EXECUTE ON FUNCTION public._allocate_receipt_number_monthly(uuid, timestamptz) FROM anon;
REVOKE EXECUTE ON FUNCTION public._sync_bill_payment_state(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.current_user_can_admin_migrations(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_admin_block_ids(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_admin_society_ids(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_bill_payment_summary(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_payment_detail(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_payment_receipt_lifecycle(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_resident_payments_v1(integer, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_society_id(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_super_admin(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_society_payments_v1(uuid, text, integer, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.migration_upload_path_ok(text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reject_offline_payment(uuid, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reverse_offline_payment(uuid, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.submit_offline_payment(uuid, text, numeric, date, text, text, text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.verify_offline_payment(uuid, text) FROM anon;